trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformPath: '$(System.DefaultWorkingDirectory)/terraform'
  terraformBackendStorageAccount: 'seryev345'
  terraformBackendContainer: 'tfstate'
  terraformBackendKey: 'terraform.tfstate'

stages:
- stage: TerraformProvisioning
  jobs:
  - job: ProvisionEC2
    displayName: 'Provision EC2 with Terraform'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - checkout: self

    - script: |
        cd $(terraformPath)
        terraform init -backend-config="storage_account_name=$(terraformBackendStorageAccount)" -backend-config="container_name=$(terraformBackendContainer)" -backend-config="key=$(terraformBackendKey)"
        terraform apply -auto-approve
      displayName: 'Terraform Apply'

- stage: KubernetesDeployment
  dependsOn: TerraformProvisioning
  jobs:
  - job: DeployServices
    displayName: 'Deploy Containerized Services with Kubernetes'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - checkout: self

    - script: |
        # Use kubectl to apply Kubernetes manifests for your web site and monitoring solution
        # Update the paths based on your project structure
        kubectl apply -f terraform/web-site-deployment.yaml
        kubectl apply -f terraform/monitoring-solution-deployment.yaml
      displayName: 'Deploy Services with Kubernetes'

    # Add additional steps for testing, monitoring, etc.

- stage: TerraformDestroy
  dependsOn: KubernetesDeployment
  jobs:
  - job: DestroyEC2
    displayName: 'Destroy EC2 with Terraform'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - checkout: self

    - script: |
        cd $(terraformPath)
        terraform destroy -auto-approve
      displayName: 'Terraform Destroy'
