apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-solution
  template:
    metadata:
      labels:
        app: monitoring-solution
    spec:
      containers:
      - name: monitoring-solution-container
        image: your-monitoring-solution-image:latest
        ports:
        - containerPort: 8080